# Generated by Django 5.2.7 on 2025-10-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='field_name',
            field=models.ImageField(default=213, upload_to='database/photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
