# Generated by Django 5.2.7 on 2025-10-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_property_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='field_name',
            new_name='image',
        ),
    ]
