# Generated by Django 5.2.7 on 2025-10-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_companies_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company_linked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='real_estate.companies'),
            preserve_default=False,
        ),
    ]
