# Generated by Django 5.2.7 on 2025-10-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
